Implement latex math mode escape enhancement
serhatgktp/pandas pull request #1
Opened 2023-03-05 20:02 UTC by ma-anwar

### Description
* Implement a new escape mode called "math-mode" that escapes all special characters inside latex strings except for any content between pairs of `$` (a math mode delimiter)

High Level Logic
```
Given a string s
Replace occurrences of \$ in s with a uuid string to preserve escaped $ signs
Split s into groups based on being surrounded by $ signs
For each group 
    if the group is in math mode (surrounded by $ and length > 1)
        leave it as is
    else
        escape the group using _escape_latex
Join all groups together into once string
Substitute back in all occurences of \$
Return parsed string
```
### Testing
TBD

2023-03-07 15:49 UTC, aydinparekh requested changes
[message.txt](https://github.com/serhatgktp/pandas/files/10911301/message.txt)
Was not able to run the tests. Error message attached. Will need to look into this. 

Other comments are pretty small and very doable.

2023-03-07 15:49 UTC, aydinparekh commented on pandas/io/formats/style_render.py
> +    else:
This line is redundant. Don't need the else statement here since the previous if statement returns.

2023-03-07 15:49 UTC, aydinparekh commented on pandas/io/formats/style_render.py
> +    s = s.replace(r"\$", r"rt8§=§4xc")
Can we change the placeholder value to a variable in the code?

2023-03-07 15:49 UTC, aydinparekh commented on pandas/io/formats/style_render.py
> +def _parse_math_mode(s):
Let's add docstring for this function.

2023-03-07 17:14 UTC, serhatgktp commented on pandas/io/formats/style_render.py
> +    else:
+1

2023-03-07 17:20 UTC, serhatgktp reviewed
Left a question

2023-03-07 18:52 UTC, ma-anwar commented on pandas/io/formats/style_render.py
> +    else:
Good call out thanks

2023-03-07 18:54 UTC, ma-anwar commented
Great catch with the existing test suite. Looks like the escape api requires new escape methods to be registered. I'll register the method before you start working on tests.

2023-03-07 18:55 UTC, ma-anwar commented on pandas/io/formats/style_render.py
> +    math mode, delimited by $.
Good point, will resolve

2023-03-07 22:33 UTC, serhatgktp commented on pandas/io/formats/style_render.py
> +    math mode, delimited by $.
"Replace special latex characters except for characters inside LaTeX math mode.
LaTeX math mode is delimited by $."

Added this suggestion so it's a little easier to understand for people with not-the-best English such as myself.

Feel free to incorporate or leave it out, it's fine either way imo.

2023-03-07 22:43 UTC, ma-anwar commented on pandas/io/formats/style_render.py
> +    math mode, delimited by $.
resolved over call

2023-03-07 22:44 UTC, ma-anwar commented
Fixed requested changes, tested using iterations of below script

```
>>> import pandas as pd
>>> df = pd.DataFrame([[1,"\$asdasd$y=9$$"],[2,"$"]], columns=["A", "B"])
>>> print(df.style.format(escape="math-mode").to_latex())
\begin{tabular}{lrl}
 & A & B \\
0 & 1 & \$asdasd$y=9$\$ \\
1 & 2 & \$ \\
\end{tabular}
```

2023-03-08 02:52 UTC, aydinparekh approved these changes
Looks great. Thank you for making those changes! I can start creating tests immediately!

2023-03-08 02:55 UTC, serhatgktp approved these changes

2023-03-08 02:57 UTC, merged